name: python ci
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
        architecture: 'x64'
    - name: Pip
      run: python -m pip install --upgrade pip
    - name: Install
      run: |
        pip install -r requirements.txt
        pip install -r test-requirements.txt
    - name: Test
      run: pytest --cov=antenny
    - name: Twine
      run: pip install twine
    - name: Dist
      run: python setup.py sdist bdist_wheel
    - name: Check
      run: twine check dist/*
    - name: Version
      id: version
      run: |
        version="$(python -c 'import antenny; print(antenny.__version__)')"
        echo "::set-output name=VERSION::$version"
    - name: Publish
      run: twine upload --non-interactive dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
    - name: Release
      id: release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version.outputs.VERSION }}
        release_name: Release ${{ steps.version.outputs.VERSION }}
        draft: false
        prerelease: false
